const BASE = `data.nba.net`

const URLS = {
    CALENDAR: () => { BASE + `/prod/v1/calendar.json`},
    SCOREBOARD: (yyyymmdd) => { BASE + `/prod/v2/${yyyymmdd}/scoreboard.json`},
    TEAMS: (yyyy) => { BASE + `/prod/v2/${yyyy}/teams.json`},
    PLAYERS: (yyyy) => { BASE + `/prod/v1/${yyyy}/players.json`},
    ALLSTARS: (yyyy) => { BASE + `/prod/v1/allstar/${yyyy}/AS_roster.json`},
    COACHES: (yyyy) => { BASE + `/prod/v1/${yyyy}/coaches.json`},
    SCHEDULE: (yyyy) => { BASE + `/prod/v1/${yyyy}/schedule.json`},
    CONFERENCE_STANDINGS: () => {BASE + `/prod/v1/current/standings_conferenc,.json`},
    DIVISION_STANDINGS: () => {BASE + `/prod/v1/current/standings_division.json`},
    LEAGUE_STANDINGS: () => {BASE + `/prod/v1/current/standings_all.json`},
    LEAGUE_STANDINGS_MINI: () => {BASE + `/prod/v1/current/standings_all_no_sort_keys.json`},
    TEAMS_STATS_LEADERS: () => {BASE + `/prod/v1/2018/team_stats_rankings.json`},
    TEAMS_STATS_LAST_FIVE_GAMES: (yyyy) => {BASE + `/prod/v1/${yyyy}/team_stats_last_five_games.json`},
    PREVIEW_ARTICLE: (yyyymmdd, gameId) => {BASE + `/prod/v1/${yyyymmdd}/${gameId}_preview_article.json`},
    GAME_BOOK_PDF: (yyyymmdd, gameId) => {BASE + `/prod/v1/${yyyymmdd}/${gameId}_Book.pdf`},
    RECAP_ARTICLE: (yyyymmdd, gameId) => {BASE + `/prod/v1/${yyyymmdd}/${gameId}_recap_article.json`},
    BOXSCORE: (yyyymmdd, gameId) => {BASE + `/prod/v1/${yyyymmdd}/${gameId}_boxscore.json`},
    BOXSCORE_MINI: (yyyymmdd, gameId) => {BASE + `/prod/v1/${yyyymmdd}/${gameId}_mini_boxscore.json`},
    PLAYBYPLAY: (yyyymmdd, gameId, period) => {BASE + `/prod/v1/${yyyymmdd}/${gameId}_pbp_${period}.json`},
    LEAD_TRACKER: (yyyymmdd, gameId, period) => {BASE + `/prod/v1/${yyyymmdd}/${gameId}_lead_tracker_${period}.json`},
    PLAYER_GAMELOG: (yyyy, personId) => {BASE + `/prod/v1/${yyyy}/players/${personId}_gamelog.json`},
    PLAYER_PROFILE: (yyyy, personId) => {BASE + `/prod/v1/${yyyy}/players/${personId}_profile.json`},
    PLAYER_UBER_STATS: (yyyy, personId) => {BASE + `/prod/v1/${yyyy}/players/${personId}_uber_stats.json`},
    TEAM_SCHEDULE_YEAR_BY_URL_CODE: (yyyy, teamUrlCode) => {BASE + `/prod/v1/${yyyy}/teams/${teamUrlCode}/schedule.json`},
    TEAMS_CONFIG: (yyyy) => {BASE + `/prod/${yyyy}/teams_config.json`},
    TEAM_ROSTER: (yyyy, teamUrlCode) => {BASE + `/prod/v1/${yyyy}/teams/${teamUrlCode}/roster.json`},
    TEAM_LEADERS_BY_URl_CODE: (yyyy, teamUrlCode) => {BASE + `/prod/v1/${yyyy}/teams/${teamUrlCode}/leaders.json`},
    TEAM_SCHEDULE_YEAR_BY_ID: (yyyy, teamId) => {BASE + `/prod/v1/${yyyy}/teams/${teamId}/schedule.json`},
    TEAM_LEADERS_BY_TEAM_ID: (yyyy, teamId) => {BASE + `/prod/v1/${yyyy}/teams/${teamId}/leaders.json`},
    TEAM_CALENDAR: (yyyy, teamId) => {`/prod/v1/${yyyy}/teams/${teamId}/schedule.json`},
    TEAM_CALENDAR_HOME_GAMES_ONLY: (yyyy, teamUrlCode) => {`/prod/v1/${yyyy}/teams/${teamUrlCode}/home_games_calendar.ics`},
    PLAYOFFS_BRACKET: (yyyy) => {`/prod/v1/${yyyy}/playoffsBracket.json`},
    PLAYOFFS_SERIES_LEADERS: (yyyy, seriesId) => {`/prod/v1/${yyyy}/playoffs_${seriesId}_leaders.json`},
}

export { URLS }; 